apiVersion: v1
kind: Service
metadata:
  name: hello-bottlerocket
  namespace: default
  labels:
    app: hello-bottlerocket
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-bottlerocket
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-bottlerocket
  labels:
    app: hello-bottlerocket
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-bottlerocket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-bottlerocket
    spec:
      containers:
      - image: {ecr_image}
        imagePullPolicy: Always
        name: hello-bottlerocket
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: nodeName
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
